layout:
    actions:
        - '@setBlockTheme':
            themes: 'js_modules_config.html.twig'
        - '@add':
            id: js_modules_config
            parentId: layout_js_modules_config
            blockType: block
        - '@add':
            id: multi_select_filter_js_modules_config
            parentId: layout_js_modules_config
            blockType: block
            options:
                visible: '=data["system_config_provider"].getValue("oro_frontend.filter_value_selectors")=="all_at_once"'
        - '@add':
            id: bootstrap_js_modules_config
            parentId: layout_js_modules_config
            blockType: block
