entry:
  stylebook-highlighter:
    - prismjs/prism.js
    - prismjs/components/prism-scss.min.js
    - prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min.js
dynamic-imports:
  orostylebook:
    - orostylebook/js/style-book/fullscreen-popup-demo-view
    - orostylebook/js/style-book/loading-mask-playground-view
    - orostylebook/js/style-book/sticky-sidebar-view
    - orostylebook/js/style-book/style-book-colors-view
    - orostylebook/js/style-book/style-book-datagrid-playground
    - orostylebook/js/style-book/style-book-dialog-widget
    - orostylebook/js/style-book/style-book-dom-relocation
    - orostylebook/js/style-book/style-book-elements-navigation-view
    - orostylebook/js/style-book/style-book-googlemaps-view
    - orostylebook/js/style-book/style-book-list-slider-view
    - orostylebook/js/style-book/style-book-playground
    - orostylebook/js/style-book/style-book-playground-widgets
    - orostylebook/js/style-book/style-book-popup-gallery-widget
    - orostylebook/js/style-book/style-book-sticky-panel-view
    - orostylebook/js/style-book/style-book-zoom-widget-view
    - orostylebook/js/style-book/toggle-action-view
    - jquery
