acls:
    oro_customer_delete:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\Customer
        category: 'customer_management'

    oro_customer_frontend_customer_user_delete:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUser
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_edit:
        type: entity
        permission: EDIT
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUser
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_customer_address_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        category: 'customer_management'

    oro_customer_customer_address_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        category: 'customer_management'

    oro_customer_customer_address_update:
        type: entity
        permission: EDIT
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        category: 'customer_management'

    oro_customer_customer_address_remove:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        category: 'customer_management'

    oro_customer_customer_user_address_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        category: 'customer_management'

    oro_customer_customer_user_address_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        category: 'customer_management'

    oro_customer_customer_user_address_update:
        type: entity
        permission: EDIT
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        category: 'customer_management'

    oro_customer_customer_user_address_remove:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        category: 'customer_management'

    oro_customer_frontend_customer_user_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUser
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_role_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserRole
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_role_update:
        type: entity
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserRole
        permission: EDIT
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_role_delete:
        type: entity
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserRole
        permission: DELETE
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_address_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        group_name: "commerce"
        category: 'customer_management'
        bindings:
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerAddressController, method: getAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerAddressController, method: cgetAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerAddressController, method: getByTypeAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerAddressController, method: getPrimaryAction}

    oro_customer_frontend_customer_address_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_address_update:
        type: entity
        permission: EDIT
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_address_remove:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerAddress
        group_name: "commerce"
        category: 'customer_management'
        bindings:
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerAddressController, method: deleteAction}

    oro_customer_frontend_customer_user_address_view:
        type: entity
        permission: VIEW
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        group_name: "commerce"
        category: 'customer_management'
        bindings:
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerUserAddressController, method: getAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerUserAddressController, method: cgetAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerUserAddressController, method: getByTypeAction}
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerUserAddressController, method: getPrimaryAction}

    oro_customer_frontend_customer_user_address_create:
        type: entity
        permission: CREATE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_address_update:
        type: entity
        permission: EDIT
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        group_name: "commerce"
        category: 'customer_management'

    oro_customer_frontend_customer_user_address_remove:
        type: entity
        permission: DELETE
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress
        group_name: "commerce"
        category: 'customer_management'
        bindings:
            - {class: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\CustomerUserAddressController, method: deleteAction}

    oro_customer_frontend_gridview_publish:
        type: action
        label: oro.grid.action.gridview_create_public.label
        description: oro.grid.action.gridview_create_public.description
        group_name: "commerce"
        bindings: ~
        category: "application"

    oro_customer_frontend_update_own_profile:
        type: action
        label: oro.customer.action.update_profile.label
        description: oro.customer.action.update_profile.description
        group_name: "commerce"
        category: "application"

    oro_customer_view_user_login_attempt:
        type: entity
        class: Oro\Bundle\CustomerBundle\Entity\CustomerUserLoginAttempt
        permission: VIEW
