api:
    entity_aliases:
        Extend\Entity\EV_Acc_Internal_Rating:
            alias:        customer_rating
            plural_alias: customer_rating
        Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
            alias:        customer_group
            plural_alias: customer_groups
        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
            alias:        customer_user_role
            plural_alias: customer_user_roles
        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            alias:        customer_user
            plural_alias: customer_users
        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress:
           alias:        customer_user_address
           plural_alias: customer_user_addresses
    entities:
        Oro\Bundle\CustomerBundle\Entity\Customer:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer.md'
            delete_handler: oro_customer.customer.handler.delete
            filters:
                fields:
                    createdAt:
                        exclude: false
                    updatedAt:
                        exclude: false
                    lifetime:
                        exclude: false
            actions:
                create:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        lifetime:
                            exclude: true
                update:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        lifetime:
                            exclude: true
            fields:
                dataChannel:
                    exclude: true
                previous_account:
                    exclude: true
        Extend\Entity\EV_Acc_Internal_Rating:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer.md'
        Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_group.md'
        Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user_role.md'
        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user.md'
            fields:
                salt:
                    exclude: true
                password:
                    exclude: true
                plainPassword:
                    exclude: true
                confirmationToken:
                    exclude: true
                emailLowercase:
                    exclude: true
            actions:
                create:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        passwordChangedAt:
                            exclude: true
                        passwordRequestedAt:
                            exclude: true
                        loginCount:
                            exclude: true
                        lastLogin:
                            exclude: true
                        password:
                            exclude: false # set manually because this field is excluded globally
                            form_options:
                                property_path: plainPassword
                                constraints:
                                    - NotNull: ~
                                    - NotBlank: ~
                update:
                    fields:
                        createdAt:
                            exclude: true
                        updatedAt:
                            exclude: true
                        passwordChangedAt:
                            exclude: true
                        passwordRequestedAt:
                            exclude: true
                        loginCount:
                            exclude: true
                        lastLogin:
                            exclude: true
        Oro\Bundle\CustomerBundle\Entity\CustomerUserAddress:
            documentation_resource: '@OroCustomerBundle/Resources/doc/api/customer_user_address.md'
            actions:
                create:
                    fields:
                        created:
                            exclude: true
                        updated:
                            exclude: true
                        systemOrganization:
                            exclude: true
                update:
                    fields:
                        created:
                            exclude: true
                        updated:
                            exclude: true
                        systemOrganization:
                            exclude: true
            subresources:
                systemOrganization:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false
                country:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false
                region:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false
