api:
    entities:
        Oro\Bundle\CustomerBundle\Entity\Customer:
            fields:
                addresses:
                    collapse: false
                    fields:
                        owner:
                            exclude: true
                        customer:
                            exclude: true
                        systemOrganization:
                            exclude: true

        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            fields:
                addresses:
                    collapse: false
                    fields:
                        owner:
                            exclude: true
                        customerUser:
                            exclude: true
                        systemOrganization:
                            exclude: true
