oro_entity:
    exclusions:
        - { entity: Oro\Bundle\CustomerBundle\Entity\CustomerUser, field: password }
        - { entity: Oro\Bundle\CustomerBundle\Entity\CustomerUser, field: salt }
        - { entity: Oro\Bundle\CustomerBundle\Entity\CustomerUser, field: confirmationToken }
        - { entity: Oro\Bundle\CustomerBundle\Entity\CustomerUserLoginAttempt, field: context }

    entity_aliases:
        Oro\Bundle\CustomerBundle\Entity\Customer:
            alias:        customer
            plural_alias: customers
        Oro\Bundle\CustomerBundle\Entity\Audit:
            alias:        customer_user_audit
            plural_alias: customer_user_audits
        Oro\Bundle\CustomerBundle\Entity\AuditField:
            alias:        customer_user_audit_field
            plural_alias: customer_user_audit_fields
        Oro\Bundle\CustomerBundle\Entity\NavigationHistoryItem:
            alias:        customer_user_navigation_history_item
            plural_alias: customer_user_navigation_history_items
        Oro\Bundle\CustomerBundle\Entity\NavigationItem:
            alias:        customer_user_navigation_item
            plural_alias: customer_user_navigation_items
        Oro\Bundle\CustomerBundle\Entity\PinbarTab:
            alias:        customer_user_pinbar_tab
            plural_alias: customer_user_pinbar_tabs
        Oro\Bundle\CustomerBundle\Entity\PageState:
            alias:        customer_user_page_state
            plural_alias: customer_user_page_states
        Oro\Bundle\CustomerBundle\Entity\WindowsState:
            alias:        customer_user_windows_state
            plural_alias: customer_user_windows_states
        Oro\Bundle\CustomerBundle\Entity\GridViewUser:
            alias:        customer_grid_view_user
            plural_alias: customer_grid_view_users
        Oro\Bundle\CustomerBundle\Entity\GridView:
            alias:        customer_grid_view
            plural_alias: customer_grid_views

    virtual_fields:
        Oro\Bundle\CustomerBundle\Entity\CustomerUser:
            contactInformation:
                query:
                    select:
                        expr: entity.email
                        return_type: string
