oro_customer:
    resource:     "@OroCustomerBundle/Controller/CustomerController.php"
    type:         annotation
    prefix:       /customer

oro_customer_address:
    resource:     "@OroCustomerBundle/Controller/CustomerAddressController.php"
    type:         annotation
    prefix:       /customer/address

oro_customer_customer_user_address:
    resource:     "@OroCustomerBundle/Controller/CustomerUserAddressController.php"
    type:         annotation
    prefix:       /customer/user/address

oro_customer_group:
    resource:     "@OroCustomerBundle/Controller/CustomerGroupController.php"
    type:         annotation
    prefix:       /customer/group

oro_customer_customer_user:
    resource: "@OroCustomerBundle/Controller/CustomerUserController.php"
    type: annotation
    prefix: /customer/user

oro_customer_customer_user_ajax:
    resource: "@OroCustomerBundle/Controller/AjaxCustomerUserController.php"
    type: annotation
    prefix: /customer/user

oro_customer_frontend_customer_user_ajax:
    resource: "@OroCustomerBundle/Controller/Frontend/AjaxCustomerUserController.php"
    type: annotation
    prefix: /customer/user
    options:
        frontend: true

oro_customer_customer_user_role:
    resource: "@OroCustomerBundle/Controller/CustomerUserRoleController.php"
    type: annotation
    prefix: /customer/user/role

oro_customer_acl_permission:
    resource: "@OroCustomerBundle/Controller/AclPermissionController.php"
    type: annotation
    prefix: /customer/acl

oro_customer_frontend_customer_user_profile:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerUserProfileController.php"
    type: annotation
    prefix: /customer/profile
    options:
        frontend: true

oro_customer_frontend_customer_user_register:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerUserRegisterController.php"
    type: annotation
    prefix: /customer/user
    options:
        frontend: true

oro_customer_frontend_customer_user:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerUserController.php"
    type: annotation
    prefix: /customer/user
    options:
        frontend: true

oro_customer_frontend_customer_user_address:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerUserAddressController.php"
    type: annotation
    prefix: /customer/user/address
    options:
        frontend: true

oro_customer_frontend_customer_address:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerAddressController.php"
    type: annotation
    prefix: /customer/user/address/customer/
    options:
        frontend: true

oro_customer_user_security:
    resource: "@OroCustomerBundle/Controller/SecurityController.php"
    type: annotation
    prefix: /customer/user
    options:
        frontend: true

oro_customer_user_password_reset:
    resource: "@OroCustomerBundle/Controller/Frontend/ResetController.php"
    type: annotation
    prefix: /customer/user
    options:
        frontend: true

oro_customer_bundle_api:
    resource:     "@OroCustomerBundle/Resources/config/oro/routing_api.yml"
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest

oro_customer_pinbar_help:
    path: /pinbar/help
    defaults: { _controller: FrameworkBundle:Template:template, template: "OroNavigationBundle:Pinbar:help.html.twig" }
    options:
        frontend: true

oro_customer_frontend_customer_user_role:
    resource: "@OroCustomerBundle/Controller/Frontend/CustomerUserRoleController.php"
    type:     annotation
    prefix:   /customer/roles
    options:
        frontend: true

oro_customer_frontend_acl_access_levels:
    path: /customer/roles/acl-access-levels/{oid}
    defaults:
        _controller: OroCustomerBundle:AclPermission:aclAccessLevels
        _format: json
    requirements:
        oid: '\w+:[\w\(\)]+'
    options:
        frontend: true

oro_frontend_autocomplete_search:
    path: /autocomplete/search
    defaults: { _controller: OroFormBundle:Autocomplete:search }
    options:
        frontend: true

oro_customer_frontend_entity_pagination_first:
    path: /entity-pagination/first/{_entityName}/{_scope}/{_routeName}"
    defaults: { _controller: OroEntityPaginationBundle:EntityPagination:first }
    options:
        frontend: true

oro_customer_frontend_entity_pagination_previous:
    path: /entity-pagination/previous/{_entityName}/{_scope}/{_routeName}"
    defaults: { _controller: OroEntityPaginationBundle:EntityPagination:previous }
    options:
        frontend: true

oro_customer_frontend_entity_pagination_next:
    path: /entity-pagination/next/{_entityName}/{_scope}/{_routeName}"
    defaults: { _controller: OroEntityPaginationBundle:EntityPagination:next }
    options:
        frontend: true

oro_customer_frontend_entity_pagination_last:
    path: /entity-pagination/last/{_entityName}/{_scope}/{_routeName}"
    defaults: { _controller: OroEntityPaginationBundle:EntityPagination:last }
    options:
        frontend: true

# Disabled as per BAP-9497.
#oro_customer_audit:
#    resource:     "@OroCustomerBundle/Controller/AuditController.php"
#    type:         annotation
#    options:
#        frontend: true
