search:
    Oro\Bundle\CustomerBundle\Entity\Customer:
        alias:                          oro_customer_customer
        route:
            name:                       oro_customer_customer_view
            parameters:
                id:                     id
        search_template:                '@OroCustomer/Customer/searchResult.html.twig'
        fields:
            -
                name:                   id
                target_type:            integer
                target_fields:          [oro_customer_id]
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
            -
                name:                   group
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           name
                        target_type:    text
                        target_fields:  [group]
            -
                name:                   parent
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:                   name
                        target_type:            text
                        target_fields:          [parentName]
            -
                name: addresses
                relation_type: one-to-many
                relation_fields:
                    -   name: street
                        target_type: text
                        target_fields: [addressStreet, address]
                    -   name: street2
                        target_type: text
                        target_fields: [addressStreet2, address]
                    -   name: city
                        target_type: text
                        target_fields: [addressCity, address]
                    -   name: country
                        relation_type: many-to-one
                        relation_fields:
                            -   name: iso2Code
                                target_type: text
                                target_fields: [addressCountry, address]
                    -   name: region
                        relation_type: many-to-one
                        relation_fields:
                            -   name: name
                                target_type: text
                                target_fields: [addressRegion, address]
                    -   name: postalCode
                        target_type: text
                        target_fields: [addressPostalCode, address]
                    -   name: firstName
                        target_type: text
                        target_fields: [addressFirstName, address]
                    -   name: lastName
                        target_type: text
                        target_fields: [addressLastName, address]

    Oro\Bundle\CustomerBundle\Entity\CustomerGroup:
        alias:                          oro_customer_group
        route:
            name:                       oro_customer_customer_group_view
            parameters:
                id:                     id
        search_template:                '@OroCustomer/CustomerGroup/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]

    Oro\Bundle\CustomerBundle\Entity\CustomerUser:
        alias: oro_customer_customer_user
        label: oro.customer.customeruser.entity_plural_label
        route:
            name: oro_customer_customer_user_view
            parameters:
                id: id
        search_template: '@OroCustomer/CustomerUser/searchResult.html.twig'
        fields:
            -
                name: email
                target_type: text
                target_fields: [email]
            -
                name: firstName
                target_type: text
                target_fields: [firstName]
            -
                name: lastName
                target_type: text
                target_fields: [lastName]
            -
                name: customer
                relation_type: many-to-one
                relation_fields:
                    -
                        name: id
                        target_type: integer
                        target_fields: [customer_id]
                    -
                        name: name
                        target_type: text
                        target_fields: [customer]
            -
                name: addresses
                relation_type: one-to-many
                relation_fields:
                    -   name: street
                        target_type: text
                        target_fields: [addressStreet, address]
                    -   name: street2
                        target_type: text
                        target_fields: [addressStreet2, address]
                    -   name: city
                        target_type: text
                        target_fields: [addressCity, address]
                    -   name: country
                        relation_type: many-to-one
                        relation_fields:
                            -   name: iso2Code
                                target_type: text
                                target_fields: [addressCountry, address]
                    -   name: region
                        relation_type: many-to-one
                        relation_fields:
                            -   name: name
                                target_type: text
                                target_fields: [addressRegion, address]
                    -   name: postalCode
                        target_type: text
                        target_fields: [addressPostalCode, address]
                    -   name: firstName
                        target_type: text
                        target_fields: [addressFirstName, address]
                    -   name: lastName
                        target_type: text
                        target_fields: [addressLastName, address]


    Oro\Bundle\CustomerBundle\Entity\CustomerUserRole:
        alias: oro_customer_customer_user_role
        label: oro.customer.customeruserrole.entity_plural_label
        route:
            name: oro_customer_customer_user_role_view
            parameters:
                id: id
        search_template: '@OroCustomer/CustomerUserRole/searchResult.html.twig'
        fields:
            -
                name: label
                target_type: text
                target_fields: [label]
