services:
    _defaults:
        public: true

    Oro\Bundle\FrontendImportExportBundle\Controller\Frontend\ExportController:
        calls:
           - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
           - { name: 'container.service_subscriber' }
