services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Oro\Bundle\FrontendImportExportBundle\Async\Topic\PreExportTopic: ~
    Oro\Bundle\FrontendImportExportBundle\Async\Topic\ExportTopic: ~
    Oro\Bundle\FrontendImportExportBundle\Async\Topic\PostExportTopic: ~
    Oro\Bundle\FrontendImportExportBundle\Async\Topic\SaveExportResultTopic: ~
