services:
    oro_frontend_importexport.handler.export_handler.stub:
        decorates: oro_frontend_importexport.handler.export_handler
        parent: oro_frontend_importexport.handler.export_handler
        public: true
