services:
    oro_frontend_importexport.async.processor.pre_export:
        class: Oro\Bundle\FrontendImportExportBundle\Async\Export\PreExportMessageProcessor
        parent: oro_importexport.async.pre_export
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_frontend_importexport.async.processor.post_export:
        class: Oro\Bundle\FrontendImportExportBundle\Async\Export\PostExportMessageProcessor
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
