services:
    oro_frontend_importexport.handler.export_handler.stub:
        decorates: oro_frontend_importexport.handler.export_handler
        parent: oro_frontend_importexport.handler.export_handler
        public: true

    oro_frontend_importexport.file.file_manager.stub:
        decorates: oro_frontend_importexport.file.file_manager
        parent: oro_frontend_importexport.file.file_manager
        public: true

    oro_frontend_importexport.manager.export_result_notification_sender.stub:
        decorates: oro_frontend_importexport.manager.export_result_notification_sender
        parent: oro_frontend_importexport.manager.export_result_notification_sender
        public: true

    oro_frontend_importexport.tests.skipped_file_systems:
        class: Oro\Bundle\GaufretteBundle\Tests\Functional\Environment\SkippedGaufretteFileSystemProvider
        decorates: oro_gaufrette.tests.skipped_file_systems
        arguments:
            - '@.inner'
            - ['frontend_importexport']
