oro_frontend_attachment_filter_image:
    path: "media/cache/attachment/filter/{filter}/{filterMd5}/{id}/{filename}"
    defaults: { _controller: Oro\Bundle\AttachmentBundle\Controller\FileController::getFilteredImageAction}
    requirements:
        id: '\d+'
        filterMd5: '^[0-9a-f]{32}$'
    options:
        frontend: true

oro_frontend_attachment_resize_image:
    path: "media/cache/attachment/resize/{id}/{width}/{height}/{filename}"
    defaults: { _controller: Oro\Bundle\AttachmentBundle\Controller\FileController::getResizedAttachmentImageAction }
    requirements:
        id: '\d+'
        width: '\d+'
        height: '\d+'
    options:
        frontend: true

oro_frontend_attachment_get_file:
    path: "attachment/{action}/{id}/{filename}"
    defaults: { _controller: Oro\Bundle\AttachmentBundle\Controller\FileController::getFileAction}
    requirements:
        id: '\d+'
        action: '(get|download)'
    options:
        frontend: true
