fa_to_svg:
    fa-file-o: add-note
    fa-exclamation-circle: alert-circle
    fa-exclamation-triangle: alert-triangle
    fa-arrow-down: arrow-down
    fa-arrow-left: arrow-left
    fa-arrow-right: arrow-right
    fa-arrow-up: arrow-up
    fa-certificate: award
    fa-book: book-open
    fa-bookmark: bookmark-filled
    fa-bookmark-o: bookmark
    fa-briefcase: briefcase
    fa-check-circle-o: check-circle
    fa-check: check
    fa-chevron-down: chevron-down
    fa-chevron-left: chevron-left
    fa-chevron-right: chevron-right
    fa-chevron-up: chevron-up
    fa-clock-o: clock
    fa-close: close
    fa-columns: columns
    fa-list: compact-list
    fa-copy: copy
    fa-credit-card: credit-card
    fa-dollar: dollar-sign
    fa-download: download
    fa-eye-slash: eye-off
    fa-eye: eye
    fa-file-text-o: file-text
    fa-filter: filter
    fa-flag: flag
    fa-folder: folder
    fa-globe: globe
    fa-th-large: grid
    fa-files-o: group
    fa-navicon: hamburger-menu
    fa-question-circle-o: help-circle
    fa-info-circle: info-filled
    fa-link: link
    fa-list-ul: list
    fa-lock: lock
    fa-sign-in: log-in
    fa-sign-out: log-out
    fa-map-marker: map-pin
    fa-map-o: map
    fa-minus-circle: minus-circle
    fa-minus: minus
    fa-ellipsis-h: more-horizontal
    fa-level-up: move
    fa-cube: package
    fa-pencil: pencil
    fa-phone: phone
    fa-plus: plus
    fa-print: printer
    fa-refresh: refresh
    fa-remove: remove-note
    fa-search: search
    fa-cog: settings
    fa-shopping-cart: shopping-cart
    fa-sliders: sliders-applied
    fa-sort: sorting
    fa-star-o: star
    fa-tag: tag
    fa-trash-o: trash
    fa-line-chart: trending-up
    fa-truck: truck
    fa-undo: undo
    fa-unlock: unlock
    fa-upload: upload
    fa-user-o: user
    fa-users: users
    fa-flash: zap
    fa-search-plus: zoom-in
    fa-search-minus: zoom-out

file_icons:
    default: add-note
    doc: file-text
    docx: file-text
    xls: download
    xlsx: download
    pdf: download
    png: download
    jpg: download
    jpeg: download
    gif: download
    mp4: download
