layout:
    actions:
        - '@setBlockTheme':
            themes: 'OroStyleBookBundle:layouts:default/oro_stylebook_group/components_config.html.twig'

    conditions: 'context["group"]=="configs"'
