layout:
    actions:
        - '@setBlockTheme':
            themes: '@OroStyleBook/layouts/default/oro_stylebook_group/components_config.html.twig'

        - '@setOption':
            id: style_book_page_title
            optionName: defaultValue
            optionValue: 'oro_stylebook.groups.configs.title'

        - '@setOption':
            id: style_book_page_description
            optionName: vars.description
            optionValue: 'oro_stylebook.groups.configs.content'

        - '@addTree':
            items:
                group_element_components_colors_view:
                    blockType: group_element
                    options:
                        anchor: colors
                        label: oro_stylebook.groups.configs.colors.title
                group_element_components_colors:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.colors.description
                        source: false
                style_book_components_color:
                    blockType: block

                group_element_components_typography_view:
                    blockType: group_element
                    options:
                        anchor: typography
                        label: oro_stylebook.groups.configs.typography.title
                group_element_components_typography:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.typography.description
                        source: false
                style_book_components_typography:
                    blockType: block
                group_element_components_custom_font_view:
                    blockType: group_element
                    options:
                        anchor: custom_font
                        label: oro_stylebook.groups.configs.custom_fonts.title
                group_element_components_custom_font:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.custom_fonts.description
                        source: false
                style_book_components_custom_font:
                    blockType: block
                group_element_components_headings_view:
                    blockType: group_element
                    options:
                        anchor: headings
                        label: oro_stylebook.groups.configs.headings.title
                group_element_components_headings:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.headings.description
                        preview: false
                        source_language: scss
                style_book_components_headings:
                    blockType: file_printer
                group_element_components_sizes_view:
                    blockType: group_element
                    options:
                        anchor: sizes
                        label: oro_stylebook.groups.configs.sizes.title
                group_element_components_sizes:
                    blockType: group_element_item
                    options:
                        preview: false
                        source_language: scss
                style_book_components_sizes:
                    blockType: file_printer

                group_element_components_functions_view:
                    blockType: group_element
                    options:
                        anchor: functions
                        label: oro_stylebook.groups.configs.functions.title
                group_element_components_functions:
                    blockType: group_element_item
                    options:
                      preview: false
                      source_language: scss
                style_book_components_functions:
                    blockType: file_printer

                group_element_components_mixins_view:
                    blockType: group_element
                    options:
                        anchor: mixins
                        label: oro_stylebook.groups.configs.mixins.title
                group_element_components_mixins:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.mixins.description
                        source: false
                style_book_scss_mixins:
                    blockType: group_list_autogenerate
                    options:
                        vars:
                            achorPrefix: 'mixins-'

                group_element_components_animation_view:
                    blockType: group_element
                    options:
                        anchor: animation
                        label: oro_stylebook.groups.configs.animation.title
                group_element_components_animation:
                    blockType: group_element_item
                    options:
                        description: oro_stylebook.groups.configs.animation.description
                style_book_components_animation:
                    blockType: block

            tree:
                style_book_content:
                    group_element_components_colors_view:
                        group_element_components_colors:
                            style_book_components_color: ~
                    group_element_components_typography_view:
                        group_element_components_typography:
                            style_book_components_typography: ~
                    group_element_components_custom_font_view:
                        group_element_components_custom_font:
                            style_book_components_custom_font: ~
                    group_element_components_headings_view:
                        group_element_components_headings:
                            style_book_components_headings: ~
                    group_element_components_sizes_view:
                        group_element_components_sizes:
                            style_book_components_sizes: ~
                    group_element_components_functions_view:
                        group_element_components_functions:
                            style_book_components_functions: ~
                    group_element_components_mixins_view:
                        group_element_components_mixins:
                            style_book_scss_mixins: ~
                    group_element_components_animation_view:
                        group_element_components_animation:
                            style_book_components_animation: ~

    conditions: 'context["group"]=="configs"'
