datagrids:
    frontend-menu-global-grid:
        source:
            type: menu-update
            scope_type: menu_frontend_visibility
        columns:
            name:
                label: oro.navigation.menuitem.name.label
        properties:
            view_link:
                route: oro_commerce_menu_global_menu_view
                type: url
                params:
                    menuName: name
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                link: view_link
                icon: eye
                rowAction: true
        options:
            toolbarOptions:
                hide: true

    frontend-menu-by-scope-grid:
        extends: frontend-menu-global-grid
