dynamic-imports:
    commons:
        - orocommercemenu/js/app/views/header-row-view
        - orocommercemenu/js/app/views/menu-traveling-view
        - oronavigation/js/app/views/navigation-menu-view
