services:
    oro_website.form.type.websiite_entity_visibility_type:
        class: 'Oro\Bundle\WebsiteBundle\Form\Type\WebsiteScopedDataType'
        arguments:
            - "@doctrine"
            - "@oro_security.acl_helper"
        tags:
            - { name: form.type, alias: oro_website_scoped_data_type }
