aliases:
    oro/select2-autocomplete-enabledlocalization-component$: orowebsite/js/app/components/select2-autocomplete-enabledlocalization-component
dynamic-imports:
    commons:
        - oro/select2-autocomplete-enabledlocalization-component
