Oro\Bundle\WebsiteBundle\Entity\Website:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name, organization ]
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
                allowEmptyString: false
        owner:
            - NotBlank: ~
        organization:
            - NotBlank: ~
