<?php

namespace Oro\Bundle\CommerceMenuBundle\Tests\Functional\Form\Extension;

use Oro\Bundle\CommerceMenuBundle\Entity\MenuUpdate as CommerceMenuUpdate;
use Oro\Bundle\FormBundle\Form\Type\OroIconType;
use Oro\Bundle\FrontendBundle\Form\Type\StorefrontIconType;
use Oro\Bundle\NavigationBundle\Entity\MenuUpdate as PlatformMenuUpdate;
use Oro\Bundle\NavigationBundle\Form\Type\MenuUpdateType;
use Oro\Bundle\TestFrameworkBundle\Test\Form\FormAwareTestTrait;
use Oro\Bundle\TestFrameworkBundle\Test\WebTestCase;

class MenuUpdateIconsExtensionTest extends WebTestCase
{
    use FormAwareTestTrait;

    private const STOREFRONT_ICONS = [
        'add-note' => 'fa-file-o',
        'alert-circle' => 'fa-exclamation-circle',
        'alert-triangle' => 'fa-exclamation-triangle',
        'arrow-down' => 'fa-arrow-down',
        'arrow-left' => 'fa-arrow-left',
        'arrow-right' => 'fa-arrow-right',
        'arrow-up' => 'fa-arrow-up',
        'award' => 'fa-certificate',
        'book-open' => 'fa-book',
        'bookmark-filled' => 'fa-bookmark',
        'bookmark' => 'fa-bookmark-o',
        'briefcase' => 'fa-briefcase',
        'check-circle' => 'fa-check-circle-o',
        'check' => 'fa-check',
        'chevron-down' => 'fa-chevron-down',
        'chevron-left' => 'fa-chevron-left',
        'chevron-right' => 'fa-chevron-right',
        'chevron-up' => 'fa-chevron-up',
        'clock' => 'fa-clock-o',
        'close' => 'fa-close',
        'columns' => 'fa-columns',
        'compact-list' => 'fa-list',
        'copy' => 'fa-copy',
        'credit-card' => 'fa-credit-card',
        'dollar-sign' => 'fa-dollar',
        'download' => 'fa-download',
        'eye-off' => 'fa-eye-slash',
        'eye' => 'fa-eye',
        'file-text' => 'fa-file-text-o',
        'filter' => 'fa-filter',
        'flag' => 'fa-flag',
        'folder' => 'fa-folder',
        'globe' => 'fa-globe',
        'grid' => 'fa-th-large',
        'group' => 'fa-files-o',
        'hamburger-menu' => 'fa-navicon',
        'help-circle' => 'fa-question-circle-o',
        'info-filled' => 'fa-info-circle',
        'link' => 'fa-link',
        'list' => 'fa-list-ul',
        'lock' => 'fa-lock',
        'log-in' => 'fa-sign-in',
        'log-out' => 'fa-sign-out',
        'map-pin' => 'fa-map-marker',
        'map' => 'fa-map-o',
        'minus-circle' => 'fa-minus-circle',
        'minus' => 'fa-minus',
        'more-horizontal' => 'fa-ellipsis-h',
        'move' => 'fa-level-up',
        'package' => 'fa-cube',
        'pencil' => 'fa-pencil',
        'phone' => 'fa-phone',
        'plus' => 'fa-plus',
        'printer' => 'fa-print',
        'refresh' => 'fa-refresh',
        'remove-note' => 'fa-remove',
        'search' => 'fa-search',
        'settings' => 'fa-cog',
        'shopping-cart' => 'fa-shopping-cart',
        'sliders-applied' => 'fa-sliders',
        'sorting' => 'fa-sort',
        'star' => 'fa-star-o',
        'tag' => 'fa-tag',
        'trash' => 'fa-trash-o',
        'trending-up' => 'fa-line-chart',
        'truck' => 'fa-truck',
        'undo' => 'fa-undo',
        'unlock' => 'fa-unlock',
        'upload' => 'fa-upload',
        'user' => 'fa-user-o',
        'users' => 'fa-users',
        'zap' => 'fa-flash',
        'zoom-in' => 'fa-search-plus',
        'zoom-out' => 'fa-search-minus',
    ];

    private const BACKOFFICE_ICONS = [
        'oro.form.icon_select.adjust' => 'fa-adjust',
        'oro.form.icon_select.address-card' => 'fa-address-card',
        'oro.form.icon_select.address-card-o' => 'fa-address-card-o',
        'oro.form.icon_select.anchor' => 'fa-anchor',
        'oro.form.icon_select.archive' => 'fa-archive',
        'oro.form.icon_select.asterisk' => 'fa-asterisk',
        'oro.form.icon_select.ban-circle' => 'fa-ban',
        'oro.form.icon_select.bar-chart' => 'fa-bar-chart-o',
        'oro.form.icon_select.barcode' => 'fa-barcode',
        'oro.form.icon_select.beaker' => 'fa-flask',
        'oro.form.icon_select.beer' => 'fa-beer',
        'oro.form.icon_select.bell' => 'fa-bell-o',
        'oro.form.icon_select.bell-alt' => 'fa-bell',
        'oro.form.icon_select.bolt' => 'fa-bolt',
        'oro.form.icon_select.book' => 'fa-book',
        'oro.form.icon_select.bookmark' => 'fa-bookmark',
        'oro.form.icon_select.bookmark-empty' => 'fa-bookmark-o',
        'oro.form.icon_select.briefcase' => 'fa-briefcase',
        'oro.form.icon_select.bug' => 'fa-bug',
        'oro.form.icon_select.building' => 'fa-building-o',
        'oro.form.icon_select.bullhorn' => 'fa-bullhorn',
        'oro.form.icon_select.bullseye' => 'fa-bullseye',
        'oro.form.icon_select.calendar' => 'fa-calendar',
        'oro.form.icon_select.calendar-empty' => 'fa-calendar-o',
        'oro.form.icon_select.camera' => 'fa-camera',
        'oro.form.icon_select.camera-retro' => 'fa-camera-retro',
        'oro.form.icon_select.certificate' => 'fa-certificate',
        'oro.form.icon_select.check' => 'fa-check-square-o',
        'oro.form.icon_select.check-empty' => 'fa-square-o',
        'oro.form.icon_select.check-minus' => 'fa-minus-square-o',
        'oro.form.icon_select.check-sign' => 'fa-check-square',
        'oro.form.icon_select.circle' => 'fa-circle',
        'oro.form.icon_select.circle-blank' => 'fa-circle-o',
        'oro.form.icon_select.cloud' => 'fa-cloud',
        'oro.form.icon_select.cloud-download' => 'fa-cloud-download',
        'oro.form.icon_select.cloud-upload' => 'fa-cloud-upload',
        'oro.form.icon_select.code' => 'fa-code',
        'oro.form.icon_select.code-fork' => 'fa-code-fork',
        'oro.form.icon_select.coffee' => 'fa-coffee',
        'oro.form.icon_select.cog' => 'fa-cog',
        'oro.form.icon_select.cogs' => 'fa-cogs',
        'oro.form.icon_select.collapse' => 'fa-caret-square-o-down',
        'oro.form.icon_select.collapse-top' => 'fa-caret-square-o-up',
        'oro.form.icon_select.comment' => 'fa-comment',
        'oro.form.icon_select.comment-alt' => 'fa-comment-o',
        'oro.form.icon_select.comments' => 'fa-comments',
        'oro.form.icon_select.comments-alt' => 'fa-comments-o',
        'oro.form.icon_select.compass' => 'fa-compass',
        'oro.form.icon_select.credit-card' => 'fa-credit-card',
        'oro.form.icon_select.crop' => 'fa-crop',
        'oro.form.icon_select.dashboard' => 'fa-tachometer',
        'oro.form.icon_select.desktop' => 'fa-desktop',
        'oro.form.icon_select.download' => 'fa-arrow-circle-o-down',
        'oro.form.icon_select.download-alt' => 'fa-download',
        'oro.form.icon_select.edit' => 'fa-pencil-square-o',
        'oro.form.icon_select.edit-sign' => 'fa-pencil-square',
        'oro.form.icon_select.ellipsis-horizontal' => 'fa-ellipsis-h',
        'oro.form.icon_select.ellipsis-vertical' => 'fa-ellipsis-v',
        'oro.form.icon_select.envelope' => 'fa-envelope',
        'oro.form.icon_select.envelope-alt' => 'fa-envelope-o',
        'oro.form.icon_select.eraser' => 'fa-eraser',
        'oro.form.icon_select.exchange' => 'fa-exchange',
        'oro.form.icon_select.exclamation' => 'fa-exclamation',
        'oro.form.icon_select.exclamation-sign' => 'fa-exclamation-circle',
        'oro.form.icon_select.expand' => 'fa-caret-square-o-right',
        'oro.form.icon_select.expand-alt' => 'fa-plus-square-o',
        'oro.form.icon_select.external-link' => 'fa-external-link',
        'oro.form.icon_select.external-link-sign' => 'fa-external-link-square',
        'oro.form.icon_select.eye-close' => 'fa-eye-slash',
        'oro.form.icon_select.eye-open' => 'fa-eye',
        'oro.form.icon_select.facetime-video' => 'fa-video-camera',
        'oro.form.icon_select.female' => 'fa-female',
        'oro.form.icon_select.fighter-jet' => 'fa-fighter-jet',
        'oro.form.icon_select.film' => 'fa-film',
        'oro.form.icon_select.filter' => 'fa-filter',
        'oro.form.icon_select.fire' => 'fa-fire',
        'oro.form.icon_select.fire-extinguisher' => 'fa-fire-extinguisher',
        'oro.form.icon_select.flag' => 'fa-flag',
        'oro.form.icon_select.flag-alt' => 'fa-flag-o',
        'oro.form.icon_select.flag-checkered' => 'fa-flag-checkered',
        'oro.form.icon_select.folder-close' => 'fa-folder',
        'oro.form.icon_select.folder-close-alt' => 'fa-folder-o',
        'oro.form.icon_select.folder-open' => 'fa-folder-open',
        'oro.form.icon_select.folder-open-alt' => 'fa-folder-open-o',
        'oro.form.icon_select.food' => 'fa-cutlery',
        'oro.form.icon_select.frown' => 'fa-frown-o',
        'oro.form.icon_select.gamepad' => 'fa-gamepad',
        'oro.form.icon_select.gear' => 'fa-gear',
        'oro.form.icon_select.gears' => 'fa-gears',
        'oro.form.icon_select.gift' => 'fa-gift',
        'oro.form.icon_select.glass' => 'fa-glass',
        'oro.form.icon_select.globe' => 'fa-globe',
        'oro.form.icon_select.group' => 'fa-users',
        'oro.form.icon_select.hdd' => 'fa-hdd-o',
        'oro.form.icon_select.headphones' => 'fa-headphones',
        'oro.form.icon_select.heart' => 'fa-heart',
        'oro.form.icon_select.heart-empty' => 'fa-heart-o',
        'oro.form.icon_select.home' => 'fa-home',
        'oro.form.icon_select.inbox' => 'fa-inbox',
        'oro.form.icon_select.info' => 'fa-info',
        'oro.form.icon_select.info-sign' => 'fa-info-circle',
        'oro.form.icon_select.key' => 'fa-key',
        'oro.form.icon_select.keyboard' => 'fa-keyboard-o',
        'oro.form.icon_select.laptop' => 'fa-laptop',
        'oro.form.icon_select.leaf' => 'fa-leaf',
        'oro.form.icon_select.legal' => 'fa-gavel',
        'oro.form.icon_select.lemon' => 'fa-lemon-o',
        'oro.form.icon_select.level-down' => 'fa-level-down',
        'oro.form.icon_select.level-up' => 'fa-level-up',
        'oro.form.icon_select.lightbulb' => 'fa-lightbulb-o',
        'oro.form.icon_select.list-alt' => 'fa-list-alt',
        'oro.form.icon_select.location-arrow' => 'fa-location-arrow',
        'oro.form.icon_select.lock' => 'fa-lock',
        'oro.form.icon_select.magic' => 'fa-magic',
        'oro.form.icon_select.magnet' => 'fa-magnet',
        'oro.form.icon_select.mail-forward' => 'fa-mail-forward',
        'oro.form.icon_select.mail-reply' => 'fa-mail-reply',
        'oro.form.icon_select.mail-reply-all' => 'fa-mail-reply-all',
        'oro.form.icon_select.male' => 'fa-male',
        'oro.form.icon_select.map-marker' => 'fa-map-marker',
        'oro.form.icon_select.meh' => 'fa-meh-o',
        'oro.form.icon_select.microphone' => 'fa-microphone',
        'oro.form.icon_select.microphone-off' => 'fa-microphone-slash',
        'oro.form.icon_select.minus' => 'fa-minus',
        'oro.form.icon_select.minus-sign' => 'fa-minus-circle',
        'oro.form.icon_select.minus-sign-alt' => 'fa-minus-square',
        'oro.form.icon_select.mobile-phone' => 'fa-mobile',
        'oro.form.icon_select.money' => 'fa-money',
        'oro.form.icon_select.moon' => 'fa-moon-o',
        'oro.form.icon_select.move' => 'fa-arrows',
        'oro.form.icon_select.music' => 'fa-music',
        'oro.form.icon_select.off' => 'fa-power-off',
        'oro.form.icon_select.ok' => 'fa-check',
        'oro.form.icon_select.ok-circle' => 'fa-check-circle-o',
        'oro.form.icon_select.ok-sign' => 'fa-check-circle',
        'oro.form.icon_select.pencil' => 'fa-pencil',
        'oro.form.icon_select.phone' => 'fa-phone',
        'oro.form.icon_select.phone-sign' => 'fa-phone-square',
        'oro.form.icon_select.picture' => 'fa-picture-o',
        'oro.form.icon_select.plane' => 'fa-plane',
        'oro.form.icon_select.plus' => 'fa-plus',
        'oro.form.icon_select.plus-sign' => 'fa-plus-circle',
        'oro.form.icon_select.plus-sign-alt' => 'fa-plus-square',
        'oro.form.icon_select.print' => 'fa-print',
        'oro.form.icon_select.pushpin' => 'fa-thumb-tack',
        'oro.form.icon_select.puzzle-piece' => 'fa-puzzle-piece',
        'oro.form.icon_select.qrcode' => 'fa-qrcode',
        'oro.form.icon_select.question' => 'fa-question',
        'oro.form.icon_select.question-sign' => 'fa-question-circle',
        'oro.form.icon_select.quote-left' => 'fa-quote-left',
        'oro.form.icon_select.quote-right' => 'fa-quote-right',
        'oro.form.icon_select.random' => 'fa-random',
        'oro.form.icon_select.refresh' => 'fa-refresh',
        'oro.form.icon_select.remove' => 'fa-times',
        'oro.form.icon_select.remove-circle' => 'fa-times-circle-o',
        'oro.form.icon_select.remove-sign' => 'fa-times-circle',
        'oro.form.icon_select.reorder' => 'fa-bars',
        'oro.form.icon_select.reply' => 'fa-reply',
        'oro.form.icon_select.reply-all' => 'fa-reply-all',
        'oro.form.icon_select.resize-horizontal' => 'fa-arrows-h',
        'oro.form.icon_select.resize-vertical' => 'fa-arrows-v',
        'oro.form.icon_select.retweet' => 'fa-retweet',
        'oro.form.icon_select.road' => 'fa-road',
        'oro.form.icon_select.rocket' => 'fa-rocket',
        'oro.form.icon_select.rss' => 'fa-rss',
        'oro.form.icon_select.rss-sign' => 'fa-rss-square',
        'oro.form.icon_select.screenshot' => 'fa-crosshairs',
        'oro.form.icon_select.search' => 'fa-search',
        'oro.form.icon_select.share' => 'fa-share-square-o',
        'oro.form.icon_select.share-alt' => 'fa-share',
        'oro.form.icon_select.share-sign' => 'fa-share-square',
        'oro.form.icon_select.shield' => 'fa-shield',
        'oro.form.icon_select.shopping-cart' => 'fa-shopping-cart',
        'oro.form.icon_select.sign-blank' => 'fa-square',
        'oro.form.icon_select.signal' => 'fa-signal',
        'oro.form.icon_select.signin' => 'fa-sign-in',
        'oro.form.icon_select.signout' => 'fa-sign-out',
        'oro.form.icon_select.sitemap' => 'fa-sitemap',
        'oro.form.icon_select.smile' => 'fa-smile-o',
        'oro.form.icon_select.sort' => 'fa-sort',
        'oro.form.icon_select.sort-by-alphabet' => 'fa-sort-alpha-asc',
        'oro.form.icon_select.sort-by-alphabet-alt' => 'fa-sort-alpha-desc',
        'oro.form.icon_select.sort-by-attributes' => 'fa-sort-amount-asc',
        'oro.form.icon_select.sort-by-attributes-alt' => 'fa-sort-amount-desc',
        'oro.form.icon_select.sort-by-order' => 'fa-sort-numeric-asc',
        'oro.form.icon_select.sort-by-order-alt' => 'fa-sort-numeric-desc',
        'oro.form.icon_select.sort-down' => 'fa-sort-desc',
        'oro.form.icon_select.sort-up' => 'fa-sort-asc',
        'oro.form.icon_select.spinner' => 'fa-spinner',
        'oro.form.icon_select.star' => 'fa-star',
        'oro.form.icon_select.star-empty' => 'fa-star-empty',
        'oro.form.icon_select.star-half' => 'fa-star-o',
        'oro.form.icon_select.star-half-empty' => 'fa-star-half-o',
        'oro.form.icon_select.star-half-full' => 'fa-star-half-full',
        'oro.form.icon_select.subscript' => 'fa-subscript',
        'oro.form.icon_select.suitcase' => 'fa-suitcase',
        'oro.form.icon_select.sun' => 'fa-sun-o',
        'oro.form.icon_select.superscript' => 'fa-superscript',
        'oro.form.icon_select.tablet' => 'fa-tablet',
        'oro.form.icon_select.tag' => 'fa-tag',
        'oro.form.icon_select.tags' => 'fa-tags',
        'oro.form.icon_select.tasks' => 'fa-tasks',
        'oro.form.icon_select.terminal' => 'fa-terminal',
        'oro.form.icon_select.thumbs-down' => 'fa-thumbs-down',
        'oro.form.icon_select.thumbs-down-alt' => 'fa-thumbs-o-down',
        'oro.form.icon_select.thumbs-up' => 'fa-thumbs-up',
        'oro.form.icon_select.thumbs-up-alt' => 'fa-thumbs-o-up',
        'oro.form.icon_select.ticket' => 'fa-ticket',
        'oro.form.icon_select.time' => 'fa-clock-o',
        'oro.form.icon_select.tint' => 'fa-tint',
        'oro.form.icon_select.trash' => 'fa-trash-o',
        'oro.form.icon_select.trophy' => 'fa-trophy',
        'oro.form.icon_select.truck' => 'fa-truck',
        'oro.form.icon_select.umbrella' => 'fa-umbrella',
        'oro.form.icon_select.unchecked' => 'fa-unchecked',
        'oro.form.icon_select.unlock' => 'fa-unlock',
        'oro.form.icon_select.unlock-alt' => 'fa-unlock-alt',
        'oro.form.icon_select.upload' => 'fa-arrow-circle-o-up',
        'oro.form.icon_select.upload-alt' => 'fa-upload',
        'oro.form.icon_select.user' => 'fa-user',
        'oro.form.icon_select.volume-down' => 'fa-volume-down',
        'oro.form.icon_select.volume-off' => 'fa-volume-off',
        'oro.form.icon_select.volume-up' => 'fa-volume-up',
        'oro.form.icon_select.warning-sign' => 'fa-exclamation-triangle',
        'oro.form.icon_select.wrench' => 'fa-wrench',
        'oro.form.icon_select.zoom-in' => 'fa-search-plus',
        'oro.form.icon_select.zoom-out' => 'fa-search-minus',
    ];

    #[\Override]
    protected function setUp(): void
    {
        $this->initClient();
    }

    public function testMenuUpdateContainsStorefrontIconFieldForCommerceMenuUpdate(): void
    {
        $formFactory = self::getContainer()->get('form.factory');
        $menuUpdate = new CommerceMenuUpdate();
        $menu = self::getContainer()->get('oro_menu.builder_chain')->get('commerce_main_menu');
        $form = $formFactory->create(
            MenuUpdateType::class,
            $menuUpdate,
            ['menu' => $menu, 'csrf_protection' => false]
        );

        self::assertFormHasField(
            $form,
            'icon',
            StorefrontIconType::class,
            ['required' => false, 'choices' => self::STOREFRONT_ICONS]
        );
    }

    public function testMenuUpdateContainsRegularIconFieldForBackofficeMenuUpdate(): void
    {
        $formFactory = self::getContainer()->get('form.factory');
        $menuUpdate = new PlatformMenuUpdate();
        $menu = self::getContainer()->get('oro_menu.builder_chain')->get('commerce_main_menu');
        $form = $formFactory->create(
            MenuUpdateType::class,
            $menuUpdate,
            ['menu' => $menu, 'csrf_protection' => false]
        );

        self::assertFormHasField(
            $form,
            'icon',
            OroIconType::class,
            ['required' => false, 'choices' => self::BACKOFFICE_ICONS]
        );
    }
}
