oro_entity:
    exclusions:
        - { entity: Oro\Bundle\CommerceMenuBundle\Entity\MenuUpdate }

    entity_aliases:
        Oro\Bundle\CommerceMenuBundle\Entity\MenuUpdate:
            alias:        commercemenumenuupdate
            plural_alias: commercemenumenuupdates
