placeholders:
    placeholders:
        view_navButtons_before:
            items:
                commerce_customer_menu_button: ~
                commerce_customer_group_menu_button: ~

    items:
        commerce_customer_menu_button:
            template: '@@OroCommerceMenu/Placeholders/customerButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\Customer)'
        commerce_customer_group_menu_button:
            template: '@@OroCommerceMenu/Placeholders/customerGroupButton.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\CustomerBundle\Entity\CustomerGroup)'
