services:
    oro_customer.layout.block_type.customer_user_awere_block:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setOptionsConfig, [{customerUser: {required: true}}]]
            - [setName, ['customer_user_awere_block']]
        tags:
             - { name: layout.block_type, alias: customer_user_awere_block }

    oro_customer.layout.block_type.customer_user_role_users_datagrid:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setOptionsConfig, [{form: {required: true}}]]
            - [setName, ['customer_user_role_users_datagrid']]
            - [setParent, ['datagrid']]
        tags:
             - { name: layout.block_type, alias: customer_user_role_users_datagrid }

    oro_customer.layout.block_type.address_book:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['address_book']]
            -
                - setOptionsConfig
                -
                    -
                        addressCreateAclResource: {default: null}
                        addressUpdateAclResource: {default: null}
                        useFormDialog: {default: false}
                        entity: {required: true}
                        componentOptions: {required: true}
        tags:
             - { name: layout.block_type, alias: address_book }

    oro_customer.layout.block_type.target_path:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setParent, ['input']]
            - [setName, ['target_path']]
            -
                - setOptionsConfig
                -
                    -
                        pathName: {default: null}
                        pathParameters: {default: []}
                        name: {default: '_target_path'}
                        type: {default: 'hidden'}
        tags:
             - { name: layout.block_type, alias: target_path }

    oro_customer.layout.block_type.failure_path:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setParent, ['input']]
            - [setName, ['failure_path']]
            -
                - setOptionsConfig
                -
                    -
                        pathName: {default: null}
                        pathParameters: {default: []}
                        name: {default: '_failure_path'}
                        type: {default: 'hidden'}
        tags:
             - { name: layout.block_type, alias: failure_path }
