services:
    _defaults:
        public: false

    Oro\Bundle\CustomerBundle\Command\GenerateCustomerUserWsseHeaderCommand:
        arguments:
            - '@doctrine'
            - '@oro_wsse_authentication.service_locator.hasher' # Created in WsseSecurityAuthenticatorFactory
        tags:
            - { name: console.command }
