services:
    _defaults:
        public: true

    OroCustomerBundleRestApiController:
        namespace: Oro\Bundle\CustomerBundle\Controller\Api\Rest\
        resource: '../../Controller/Api/Rest/*Controller.php'
        calls:
            - [setContainer, ['@service_container']]

    OroCustomerBundleFrontendRestApiController:
        namespace: Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\
        resource: '../../Controller/Frontend/Api/Rest/*Controller.php'
        calls:
            - [setContainer, ['@service_container']]

    Oro\Bundle\CustomerBundle\Controller\Frontend\Api\Rest\EntityDataController:
        arguments:
            - '@oro_entity.routing_helper'
            - '@oro_security.entity_security_metadata_provider'
        calls:
            - [setContainer, ['@service_container']]
