services:
    oro_customer_customer.form.type.customer:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerType'
        arguments:
          - '@event_dispatcher'
          - '@security.authorization_checker'
        calls:
            - [setAddressClass, ['%oro_customer.entity.customer_address.class%']]
        tags:
            - { name: form.type, alias: oro_customer_type }

    oro_customer.form.type.customer_group:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerGroupType'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_group.class%']]
            - [setCustomerClass, ['%oro_customer.entity.customer.class%']]
        tags:
            - { name: form.type, alias: oro_customer_group_type }

    oro_customer_customer.form.type.customer_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerSelectType'
        tags:
            - { name: form.type, alias: oro_customer_customer_select }

    oro_customer_customer.form.type.frontend.owner_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendOwnerSelectType'
        arguments:
             - '@oro_security.acl_helper'
             - '@doctrine'
             - '@oro_entity_config.provider.ownership'
        tags:
            - { name: form.type, alias: oro_customer_frontend_owner_select }

    oro_customer.form.type.customer_group_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerGroupSelectType'
        tags:
            - { name: form.type, alias: oro_customer_customer_group_select }

    oro_customer.form.type.parent_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\ParentCustomerSelectType'
        tags:
            - { name: form.type, alias: oro_customer_parent_select }

    oro_customer.form.type.customer_user_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserSelectType'
        tags:
            - { name: form.type, alias: oro_customer_customer_user_select }

    oro_customer.form.type.frontend.customer_user_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserSelectType'
        arguments:
             - '@oro_security.acl_helper'
             - '@doctrine'
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_select }

    oro_customer.form.type.customer_user_multiselect_type:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserMultiSelectType'
        tags:
            - { name: form.type, alias: oro_customer_customer_user_multiselect }

    oro_customer.form.type.frontend.customer_user_multiselect_type:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\Frontend\CustomerUserMultiSelectType'
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_multiselect }

    oro_customer.form.type.customer_user:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserType'
        arguments:
            - '@security.authorization_checker'
            - '@oro_security.token_accessor'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user.class%']]
            - [setAddressClass, ['%oro_customer.entity.customer_user_address.class%']]
        tags:
            - { name: form.type, alias: oro_customer_customer_user }

    oro_customer.form.type.customer_user_role_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserRoleSelectType'
        arguments:
            - '@translator'
        calls:
            - [setRoleClass, ['%oro_customer.entity.customer_user_role.class%']]
        tags:
            - { name: form.type, alias: oro_customer_customer_user_role_select }

    oro_customer.form.type.customer_user_role:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserRoleType'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user_role.class%']]
        tags:
            - { name: form.type, alias: oro_customer_customer_user_role }

    oro_customer.form.type.frontend.customer_user_role:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserRoleType'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user_role.class%']]
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_role }

    oro_customer.form.type.frontend.customer_user_profile:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserProfileType'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user.class%']]
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_profile }

    oro_customer.form.type.frontend.customer_user:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserType'
        arguments:
            - '@security.authorization_checker'
            - '@oro_security.token_accessor'
        calls:
            - [setCustomerUserClass, ['%oro_customer.entity.customer_user.class%']]
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user }

    oro_customer.form.type.frontend.customer_user_role_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserRoleSelectType'
        arguments:
            - '@oro_security.token_accessor'
            - '@doctrine'
            - '@oro_security.acl_helper'
        calls:
            - [setRoleClass, ['%oro_customer.entity.customer_user_role.class%']]
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_role_select }

    oro_customer.form.type.frontend.customer_user.register:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserRegistrationType'
        arguments:
            - '@oro_config.manager'
            - '@oro_user.manager'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user.class%']]
        tags:
            - { name: form.type, alias: oro_customer_frontend_customer_user_register }

    oro_customer.form.type.frontend.customer_user.password_request:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserPasswordRequestType'
        tags:
            - { name: form.type, alias: oro_customer_customer_user_password_request }

    oro_customer.form.type.frontend.customer_user.password_reset:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserPasswordResetType'
        calls:
            - [setDataClass, ['%oro_customer.entity.customer_user.class%']]
        tags:
            - { name: form.type, alias: oro_customer_customer_user_password_reset }

    oro_customer.form.handler.update_customer_user_role:
        parent: oro_user.form.handler.abstract.acl_role
        class: 'Oro\Bundle\CustomerBundle\Form\Handler\CustomerUserRoleUpdateHandler'
        shared: false
        calls:
            - [setRequestStack, ['@request_stack']]
            - [setOwnershipConfigProvider, ['@oro_entity_config.provider.ownership']]
            - [setChainMetadataProvider, ['@oro_security.owner.metadata_provider.chain']]
            - [setDoctrineHelper, ['@oro_entity.doctrine_helper']]
            - [addExtensionFilter, ['entity', 'commerce']]
            - [addExtensionFilter, ['action', 'commerce']]
            - [setConfigurableName, ['commerce']]

    oro_customer.form.handler.update_customer_user_role_frontend:
        parent: oro_customer.form.handler.update_customer_user_role
        class: 'Oro\Bundle\CustomerBundle\Form\Handler\CustomerUserRoleUpdateFrontendHandler'
        shared: false
        calls:
            - [setTokenStorage, ['@security.token_storage']]
            - [setConfigurableName, ['commerce_frontend']]

    oro_customer.form.type.typed_address:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerTypedAddressType'
        calls:
             - [setDataClass, ['%oro_customer.entity.customer_address.class%']]
             - [setAddressTypeDataClass, ['%oro_address.address.type.entity.class%']]
        tags:
             - { name: form.type, alias: oro_customer_typed_address}

    oro_customer.form.type.frontend.typed_address:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerTypedAddressType'
        calls:
             - [setDataClass, ['%oro_customer.entity.customer_address.class%']]
             - [setAddressTypeDataClass, ['%oro_address.address.type.entity.class%']]
        tags:
             - { name: form.type, alias: oro_customer_frontend_typed_address}

    oro_customer.form.type.customer_user_typed_address:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerUserTypedAddressType'
        calls:
             - [setDataClass, ['%oro_customer.entity.customer_user_address.class%']]
             - [setAddressTypeDataClass, ['%oro_address.address.type.entity.class%']]
        tags:
             - { name: form.type, alias: oro_customer_customer_user_typed_address}

    oro_customer.form.type.frontend.customer_user_typed_address:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\FrontendCustomerUserTypedAddressType'
        calls:
             - [setDataClass, ['%oro_customer.entity.customer_user_address.class%']]
             - [setAddressTypeDataClass, ['%oro_address.address.type.entity.class%']]
        tags:
             - { name: form.type, alias: oro_customer_frontend_customer_user_typed_address}

    oro_customer.form.type.typed_address_with_default:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerTypedAddressWithDefaultType'
        arguments: ['@translator']
        calls:
             - [setRegistry, ['@doctrine']]
        tags:
             - { name: form.type, alias: oro_customer_typed_address_with_default}

    oro_customer.form.type.acl_access_level_text:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerAclAccessLevelTextType'
        arguments:
            - '@oro_customer.acl.resolver.role_translation_prefix'
        tags:
             - { name: form.type, alias: oro_customer_acl_access_level_text }

    oro_customer.form.extension.acl_permission:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\AclAccessLevelSelectorExtension'
        arguments:
            - '@oro_customer.acl.resolver.role_translation_prefix'
        tags:
            - { name: form.type_extension, alias: oro_acl_access_level_selector }

    oro_customer.form.extension.select_or_create_inline:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\OroEntitySelectOrCreateInlineExtension'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type_extension, alias: "oro_entity_create_or_select_inline" }

    oro_customer.form.extension.frontend_product_select:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\FrontendProductSelectExtension'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type_extension, alias: oro_product_select }

    oro_customer.form.extension.address:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\AddressExtension'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type_extension, alias: "oro_address" }

    oro_customer.form.extension.customer_scope:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\CustomerScopeExtension'
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\ScopeBundle\Form\Type\ScopeType }

    oro_customer.form.extension.customer_group_scope:
        class: 'Oro\Bundle\CustomerBundle\Form\Extension\CustomerGroupScopeExtension'
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\ScopeBundle\Form\Type\ScopeType }

    oro_customer.form.type.oro_customer_visitor_email_address:
        class: 'Oro\Bundle\CustomerBundle\Form\Type\CustomerVisitorEmailAddressType'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: form.type, alias: oro_customer_visitor_email_address }
