services:
    _instanceof:
        Psr\Log\LoggerAwareInterface:
            calls:
                - [setLogger, ['@logger']]
            tags:
                - { name: monolog.logger, channel: oro_customer }

        Oro\Component\MessageQueue\Client\TopicSubscriberInterface:
            tags:
                - { name: oro_message_queue.client.message_processor }

    oro_customer.clear_lost_customer_users_processor:
        class: Oro\Bundle\CustomerBundle\Migrations\Schema\v1_14\ClearLostCustomerUsers
        arguments:
            - '@oro_message_queue.message_producer'
            - '@oro_entity.orm.native_query_executor_helper'

    oro_customer.async.owner_tree_cache_job_processor:
        class: Oro\Bundle\CustomerBundle\Async\OwnerTreeCacheJobProcessor
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@doctrine'
            - '@oro_customer.owner.frontend_ownership_metadata_provider'
            - '@oro_customer.model.business_unit_message_factory'

    oro_customer.async.business_unit_owner_tree_cache_job_processor:
        class: Oro\Bundle\CustomerBundle\Async\BusinessUnitOwnerTreeCacheJobProcessor
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_customer.owner.tree_provider'
            - '@oro_customer.model.business_unit_message_factory'
