config:
    paths:
        'orocustomer/js/app/components/customer-user-component': 'bundles/orocustomer/js/app/components/customer-user-component.js'
        'orocustomer/js/app/components/customer-address-component': 'bundles/orocustomer/js/app/components/customer-address-component.js'
        'orocustomer/js/app/components/customer-address-book-component': 'bundles/orocustomer/js/app/components/customer-address-book-component.js'
        'orocustomer/js/app/components/customer-user-role-component': 'bundles/orocustomer/js/app/components/customer-user-role-component.js'
        'orocustomer/js/app/components/customer-selection-component': 'bundles/orocustomer/js/app/components/customer-selection-component.js'
        'oro/select2-autocomplete-customeruser-component': 'bundles/orocustomer/js/app/components/select2-autocomplete-customeruser-component.js'
        'orocustomer/js/app/views/customer-role-view': 'bundles/orocustomer/js/app/views/customer-role-view.js'
