services:
    oro_commercemenu.layout.block_type.menu:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['menu']]
            -
                - setOptionsConfig
                -
                    -
                        item: {required: true}
                        depth: {default: null}
                        matchingDepth: {default: null}
                        currentAsLink: {default: true}
                        currentClass: {default: 'current'}
                        ancestorClass: {default: 'current_ancestor'}
                        firstClass: {default: 'first'}
                        lastClass: {default: 'last'}
                        allow_safe_labels: {default: false}
                        clear_matcher: {default: true}
                        leaf_class: {default: null}
                        branch_class: {default: null}
                        child_attr: {default: []}
                        link_attr: {default: []}
                        label_attr: {default: []}
                        customItemBlock: {default: null}

        tags:
            - { name: layout.block_type, alias: menu }

    oro_menu.layout.block_type.menu_list:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['menu_list']]
            -
                - setOptionsConfig
                -
                    -
                        layoutType: {default: null}
                        tagName: {default: 'ul'}
        tags:
            - { name: layout.block_type, alias: menu_list }

    oro_menu.layout.block_type.menu_item:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['menu_item']]
            -
                - setOptionsConfig
                -
                    -
                        tagName: {default: 'li'}
                        iconEnable: {default: true}
                        linkEnable: {default: true}
                        tooltipEnable: {default: false}
                        dividerEnable: {default: true}
                        imageViewAs: {default: 'line'}
        tags:
            - { name: layout.block_type, alias: menu_item }

    oro_menu.layout.block_type.menu_item_simple:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['menu_item_simple']]
            -
                - setOptionsConfig
                -
                    -
                        tagName: {default: 'li'}
                        iconEnable: {default: true}
                        linkEnable: {default: true}
                        dividerEnable: {default: true}
                        imageViewAs: {default: 'line'}
        tags:
            - { name: layout.block_type, alias: menu_item_simple }

    oro_menu.layout.block_type.menu_inner:
        parent: oro_layout.block_type.abstract_configurable_container
        calls:
            - [setName, ['menu_inner']]
            -
                - setOptionsConfig
                -
                    -
                        layoutType: {default: null}
        tags:
            - { name: layout.block_type, alias: menu_inner }
