api:
    entity_aliases:
        Oro\Bundle\ApiBundle\Model\EntityIdentifier:
            alias:        entityidentifier
            plural_alias: entityidentifiers

    entities:
        Oro\Bundle\ApiBundle\Model\EntityIdentifier:
            identifier_field_names: [id]
            fields:
                # this is a predefined field name that is used to provide
                # the class name of the target entity
                # @see \Oro\Component\EntitySerializer\ConfigUtil::CLASS_NAME
                # @see \Oro\Bundle\ApiBundle\Request\DocumentBuilder\ObjectAccessorInterface::getClassName
                __class__:
                    meta_property: true
                    data_type: string
                # the identifier of the target entity
                id:
                    data_type: string
            # this entity does not have own API resource
            actions: false

        Oro\Bundle\AddressBundle\Entity\AddressType:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/address_type.md'
            filters:
                fields:
                    name:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\AddressBundle\Entity\Region:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/region.md'
            filters:
                fields:
                    combinedCode:
                        allow_array: true
                    country:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\AddressBundle\Entity\Country:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/country.md'
            fields:
                regions:
                    max_results: -1
            filters:
                fields:
                    iso2Code:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
