features:
    frontend_web_api:
        label: oro_frontend.system_configuration.fields.web_api.label
        toggle: oro_frontend.web_api
        routes:
            - oro_frontend_rest_api_doc
            - oro_frontend_rest_api_doc_resource
            - oro_frontend_rest_api_doc_not_allowed
            - oro_frontend_rest_api_doc_resource_not_allowed
