features:
    frontend_web_api:
        label: oro_frontend.web_api.feature.label
        description: oro_frontend.web_api.feature.description
        toggle: oro_frontend.web_api
        routes:
            - oro_frontend_rest_api_doc
            - oro_frontend_rest_api_doc_resource
