oro_frontend_rest_api_doc:
    path: '%oro_api.rest.prefix%doc/{view}'
    controller: Oro\Bundle\ApiBundle\Controller\RestApiDocController::indexAction
    requirements:
        view: '[\w-]+'
    defaults:
        view: frontend_rest_json_api
    options:
        frontend: true

oro_frontend_rest_api_doc_resource:
    path: '%oro_api.rest.prefix%doc/{view}/{resource}'
    controller: Oro\Bundle\ApiBundle\Controller\RestApiDocController::resourceAction
    requirements:
        view: '[\w-]+'
    options:
        frontend: true

# * GET method: returns an entity of the given type by its identifier
# * DELETE method: deletes an entity of the given type by its identifier
# * PATCH method: updates the specified fields of the given entity
oro_frontend_rest_api_item:
    path: '%oro_api.rest.prefix%{entity}/{id}'
    controller: Oro\Bundle\FrontendBundle\Controller\FrontendRestApiController::itemAction
    requirements:
        entity: (?:(?!(rest)(/|$))[^/]+)
    options:
        frontend: true
        group: frontend_rest_api
        priority: -10

# * GET method: returns a list of entities of the given type
# * DELETE method: deletes a list of entities of the given type by the given filters
# * POST method: creates an entity of the given type
# * PATCH method: updates or creates a list of entities of the given type
oro_frontend_rest_api_list:
    path: '%oro_api.rest.prefix%{entity}'
    controller: Oro\Bundle\FrontendBundle\Controller\FrontendRestApiController::listAction
    requirements:
        entity: (?:(?!(rest)(/|$))[^/]+)
    options:
        frontend: true
        group: frontend_rest_api
        priority: -10

# * GET method: returns an entity (for to-one association)
#   or a list of entities (for to-many association)
#   connected to the given entity by the given association
# * PATCH method: updates an entity (or entities, it depends on the association type) connected
#   to the given entity by the given association.
#   This type of the request is non-standard and do not have default implementation,
#   additional processors should be added for each association requires it.
# * POST method: adds an entity (or entities, it depends on the association type) connected
#   to the given entity by the given association.
#   This type of the request is non-standard and do not have default implementation,
#   additional processors should be added for each association requires it.
# * DELETE method: deletes an entity (or entities, it depends on the association type) connected
#   to the given entity by the given association.
#   This type of the request is non-standard and do not have default implementation,
#   additional processors should be added for each association requires it.
oro_frontend_rest_api_subresource:
    path: '%oro_api.rest.prefix%{entity}/{id}/{association}'
    controller: Oro\Bundle\FrontendBundle\Controller\FrontendRestApiController::subresourceAction
    requirements:
        entity: (?:(?!(rest)(/|$))[^/]+)
    options:
        frontend: true
        group: frontend_rest_api
        priority: -10

# * GET method: returns an entity identifier (for to-one association)
#   or a list of entity identifiers (for to-many association)
#   connected to the given entity by the given association
# * PATCH method: updates a relationship between entities represented by the given association
#   for to-one association the target entity can be NULL to clear the association
#   for to-many association the existing relationships will be completely replaced with the specified list
# * POST method: adds the specified entities to the relationship represented by the given to-many association
# * DELETE method: deletes the specified entities from the relationship represented by the given to-many association
oro_frontend_rest_api_relationship:
    path: '%oro_api.rest.prefix%{entity}/{id}/relationships/{association}'
    controller: Oro\Bundle\FrontendBundle\Controller\FrontendRestApiController::relationshipAction
    requirements:
        entity: (?:(?!(rest)(/|$))[^/]+)
    options:
        frontend: true
        group: frontend_rest_api
        priority: -10
